name: docker

on:
  push:
    tags-ignore:
      - v*-*-*
  pull_request:

jobs:
  build:
    name: Build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.4

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.3.0
        with:
          username: godsun
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: godsun/proxypool/proxypool
          tag_with_ref: true
